const test=require('node:test'),assert=require('node:assert/strict'),H=require('./helpers.cjs'),C=H.C,A=require('../lib/azure-client.js'),E=require('../lib/entra-applications.js'),R=require('../lib/refresh.js'),S=require('../lib/selection.js');
const cfg={tenantId:H.tenant,subscriptionIds:[H.sub]},prefix='/subscriptions/'+H.sub+'/resourceGroups/rg-test';
const rg={id:prefix,type:'Microsoft.Resources/resourceGroups',name:'rg-test'};
const site={id:prefix+'/providers/Microsoft.Web/sites/app',type:'Microsoft.Web/sites',name:'app',kind:'functionapp'};
const bus={id:prefix+'/providers/Microsoft.ServiceBus/namespaces/bus',type:'Microsoft.ServiceBus/namespaces',name:'bus',sku:{tier:'Standard'}};
const fn={id:site.id+'/functions/run',type:site.type+'/functions',name:'app/run'};
const queue={id:bus.id+'/queues/jobs',type:bus.type+'/queues',name:'jobs'};
const topic={id:bus.id+'/topics/events',type:bus.type+'/topics',name:'events'};
const rows=[site,bus,H.raw],map=C.mappings([[fn.type,'technology-function']]);
function fake(options={}){const calls=[];return {calls,now:()=>Date.parse('2026-09-28T11:00:00Z'),sleep:()=>{},request:(method,url)=>{calls.push([method,url]);const u=new URL(url),p=decodeURIComponent(u.pathname);if(p==='/subscriptions/'+H.sub)return H.ok(H.info);if(/\/resourcegroups$/i.test(p))return H.page([rg]);if(/\/providers$/.test(p))return H.page([{namespace:'Microsoft.Compute',resourceTypes:[{resourceType:'virtualMachines',apiVersions:['2025-01-01']}]}]);if(/\/resources$/.test(p)){const filter=u.searchParams.get('$filter');return H.page(rows.filter(r=>!filter||filter===`resourceType eq '${C.lower(r.type)}'`));}if(p===bus.id+'/queues')return options.denyQueue?{status:403}:H.page(options.noQueue?[]:[queue]);if(p===bus.id+'/topics')return H.page([topic]);if(p===site.id+'/functions')return H.page([fn]);if(p===queue.id&&options.noQueue)return {status:404,body:{error:{code:'MessagingEntityNotFound'}}};const r=rows.concat([fn,queue,topic]).find(r=>r.id===p);if(r)return H.ok({...r,properties:{hardwareProfile:{vmSize:'Standard_B2s'},adminPassword:'SECRET'}});throw Error('Unexpected request '+url);}};}
function asExisting(plan){return plan.operations.filter(op=>op.name!==undefined).map((op,i)=>({id:'archi-'+i,type:op.base,name:op.name,properties:{...op.properties}}));}
function sync(existing,types,io=fake()){const opts={selectedTypes:types,enrichInfrastructure:true};const s=A.create(io,{...H.token,expiresAt:9999999999999}).inventory(cfg,existing,opts);return {s,p:C.plan(existing,s,map,opts),io};}
test('type scopes normalize case and reject empty or malformed selections',()=>{assert.deepEqual(C.settings({selectedTypes:[fn.type,fn.type.toUpperCase()]}).selectedTypes,[C.lower(fn.type)]);for(const selectedTypes of [[],[''],["Microsoft.Web/sites' or true"],false])assert.throws(()=>C.settings({selectedTypes}),/Select at least/);assert.equal(C.settings().selectedTypes,null);});
test('first run selects Functions and queues, includes necessary parents, skips topics and unrelated resources',()=>{const r=sync([],[fn.type,queue.type]);assert.deepEqual(r.s.resources.map(x=>x.type).sort(),[rg.type,'Microsoft.Resources/subscriptions',site.type,bus.type,fn.type,queue.type].sort());assert.ok(!r.io.calls.some(c=>c[1].includes('/topics?')));assert.equal(r.io.calls.filter(c=>c[1].includes('/resources?')).length,2);assert.ok(r.io.calls.filter(c=>c[1].includes('/resources?')).every(c=>c[1].includes('$filter=')));assert.ok(r.p.relationships.pairs.some(x=>x.type==='serving-relationship'));});
test('switching to VM type preserves earlier Functions and queues without even checking their existence',()=>{const first=sync([],[fn.type,queue.type]),old=asExisting(first.p),before=JSON.stringify(old),r=sync(old,[H.raw.type]);assert.equal(r.p.counts.deleted,0);assert.ok(!r.p.operations.some(op=>[fn.id,queue.id,site.id,bus.id].includes(op.properties['Azure-ObjectId'])));assert.equal(JSON.stringify(old),before);assert.ok(!r.io.calls.some(c=>/Microsoft.Web|Microsoft.ServiceBus|\/functions|\/queues|\/topics/i.test(c[1])));assert.equal(r.p.counts.created,1);});
test('selected type missing in a complete scope is soft-deleted; unselected Function remains preserved',()=>{const old=asExisting(sync([],[fn.type,queue.type]).p),r=sync(old,[queue.type],fake({noQueue:true}));const q=old.find(e=>e.properties['Azure-ObjectId']===queue.id),f=old.find(e=>e.properties['Azure-ObjectId']===fn.id);assert.equal(r.p.operations.find(op=>op.elementId===q.id).action,'deleted');assert.ok(!r.p.operations.some(op=>op.elementId===f.id));});
test('denied selected collection does not mark selected or unselected resources deleted',()=>{const old=asExisting(sync([],[fn.type,queue.type]).p),r=sync(old,[queue.type],fake({denyQueue:true}));assert.equal(r.p.partial,true);assert.equal(r.p.counts.deleted,0);});
test('selecting a parent type alone does not list any of its child collections',()=>{const r=sync([],[site.type,bus.type]);assert.ok(!r.io.calls.some(c=>/\/(queues|topics|functions)\?/.test(c[1])));assert.equal(r.s.resources.length,4);});
test('planner refuses scope mismatch rather than interpreting filtered absence as deletion',()=>{const r=sync([],[queue.type]);assert.throws(()=>C.plan([],r.s,map,{selectedTypes:null,enrichInfrastructure:true}),/type scopes disagree/);});
test('checkbox selections survive filtering; clearing means none rather than all',()=>{const rows=S.typeRows(map,[],{includeEntraApplications:true,enrichInfrastructure:true}),s=S.state(rows,[]);s.check(C.lower(fn.type),true);assert.equal(s.visible('service bus queue').length,1);s.check(C.lower(queue.type),true);assert.deepEqual(s.ids().sort(),[C.lower(fn.type),C.lower(queue.type)].sort());s.clear();assert.deepEqual(s.ids(),[]);assert.throws(()=>s.check('not-a-row',true),/Unknown/);});
test('selector offers existing uncatalogued types and hides explicitly disabled features',()=>{const e=H.existing();const rows=S.typeRows({},[e],{includeEntraApplications:false,enrichInfrastructure:false});assert.ok(rows.some(r=>r.id===C.lower(H.raw.type)));assert.ok(!rows.some(r=>r.id===C.lower(C.ENTRA_APPLICATION_TYPE)||r.id.endsWith('/subnets')));});
test('property refresh performs individual ARM GETs, not inventory enumeration or configuration reads',()=>{const old=H.existing(),io=fake(),s=A.create(io,{...H.token,expiresAt:9999999999999}).refresh(cfg,[old],{enrichInfrastructure:true}),p=R.plan([old],s,{enrichInfrastructure:true});assert.equal(p.operations.length,1);assert.equal(p.operations[0].elementId,old.id);assert.equal(p.operations[0].properties['Azure-VMSize'],'Standard_B2s');assert.ok(!JSON.stringify(s).includes('SECRET'));assert.ok(!io.calls.some(c=>/\/(resources|resourcegroups|functions|queues|config)\?/i.test(c[1])));assert.equal(p.counts.created,0);assert.equal(p.counts.deleted,0);});
test('property refresh preserves missing and denied objects and advances only readable timestamps',()=>{for(const status of [403,404]){const old=H.existing(),second={...old,id:'second',properties:{...old.properties,'Azure-ObjectId':H.id+'2','Azure-ObjectName':'vm-2'}},io=H.io([H.ok(H.info),H.page([{namespace:'Microsoft.Compute',resourceTypes:[{resourceType:'virtualMachines',apiVersions:['2025-01-01']}]}]),{status,body:{error:{code:'ResourceNotFound'}}},H.ok({...H.raw,id:H.id+'2',name:'vm-2'})]);const s=A.create(io,H.token).refresh(cfg,[old,second],{}),p=R.plan([old,second],s,{});assert.equal(p.partial,true);assert.equal(p.operations.length,1);assert.equal(p.operations[0].elementId,'second');assert.equal(p.skipped,1);assert.equal(p.counts.deleted,0);assert.equal(old.properties.IsDeleted,'no');}});
test('property refresh planner refuses a resource not already selected in the model',()=>{assert.throws(()=>R.plan([],H.snapshot(),{}),/cannot create/);});
test('property refresh uses existing base types rather than requesting catalog conversion',()=>{const old=H.existing();old.type='device';const p=R.plan([old],H.snapshot(),{});assert.equal(p.operations[0].base,'device');});
test('Graph property refresh uses only selected object GETs with projected fields',()=>{const id=H.clientId,app={id,appId:H.tenant,displayName:'Registered app'},snap={tenantId:H.tenant,completed:true,applications:[app],confirmedMissing:[],collectedAt:H.snapshot().collectedAt};const op=E.plan([],snap,{}).operations[0],old={id:'app-element',name:op.name,type:'node',properties:op.properties},io=H.io([H.ok({...app,passwordCredentials:[{secretText:'SECRET'}]})]);const s=E.create(io,{...H.token,resource:'graph',tenantId:H.tenant}).refresh(H.tenant,[old]);assert.equal(io.calls.length,1);assert.ok(io.calls[0][1].includes('/applications/'+id+'?$select=id,appId,displayName'));assert.ok(!JSON.stringify(s).includes('SECRET'));const p=R.plan([old],{...H.snapshot([]),entraApplications:s},{});assert.equal(p.operations[0].elementId,'app-element');assert.equal(p.counts.created,0);});
test('Graph missing or denied property reads preserve the existing application',()=>{for(const status of [403,404]){const app={id:H.clientId,appId:H.tenant,displayName:'App'},snap={tenantId:H.tenant,completed:true,applications:[app],confirmedMissing:[],collectedAt:H.snapshot().collectedAt},op=E.plan([],snap,{}).operations[0],old={id:'app',type:'node',properties:op.properties},io=H.io([{status,body:{error:{code:'Request_ResourceNotFound'}}}]),s=E.create(io,{...H.token,resource:'graph',tenantId:H.tenant}).refresh(H.tenant,[old]);const p=R.plan([old],{...H.snapshot([]),entraApplications:s},{});assert.equal(p.operations.length,0);assert.equal(p.skipped,1);assert.equal(p.partial,true);}});
test('one denied resource-type filter cannot block other selected types in the subscription or group fallback',()=>{
 const base=fake(),calls=[],io={...base,calls,request:(method,url)=>{calls.push([method,url]);if(new URL(url).searchParams.get('$filter')==="resourceType eq 'microsoft.compute/virtualmachines'")return {status:403};return base.request(method,url);}};
 const r=sync([],[H.raw.type,fn.type],io);assert.equal(r.p.partial,true);assert.ok(r.s.resources.some(r=>r.id===fn.id));assert.equal(r.p.counts.deleted,0);assert.ok(calls.some(c=>c[1].includes('/functions?')));
});

test('properties-only refresh still updates base properties of existing subnets when enrichment is disabled',()=>{
 const raw={id:prefix+'/providers/Microsoft.Network/virtualNetworks/vnet/subnets/app',type:'Microsoft.Network/virtualNetworks/subnets',name:'app'},resource=C.normalize(raw,H.info,H.tenant),snap=H.snapshot([resource]),op=C.plan([],snap,{}, {enrichInfrastructure:true}).operations[0],old={id:'subnet',type:op.base,name:op.name,properties:op.properties};const p=R.plan([old],snap,{enrichInfrastructure:false});assert.equal(p.operations.length,1);assert.equal(p.operations[0].elementId,'subnet');assert.equal(p.skipped,0);
});
